-- Aanmaken database
CREATE DATABASE event_planner;

--  Database gebruiken
USE event_planner

-- Tabel Users aanmaken
CREATE TABLE USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

-- Tabel Events aanmaken
CREATE TABLE EVENTS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION TEXT,
    EVENT_DATE DATE NOT NULL,
    LOCATION VARCHAR(150),
    STATUS BOOL NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)
